var terms = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut tempor quam. Praesent suscipit erat vel dolor sodales pharetra. Morbi quis ipsum vulputate, placerat purus viverra, facilisis sem. Vestibulum imperdiet ac risus vel cursus. Curabitur interdum elementum vehicula. Curabitur fermentum, urna eu aliquet ultrices, sem lectus pretium urna, vel rhoncus nunc arcu quis justo. Mauris massa turpis, vulputate sit amet feugiat ut, cursus ut quam. Pellentesque vel nisl in lectus pretium lacinia in ut massa. Sed augue felis, tristique viverra imperdiet ac, sollicitudin nec elit. Curabitur a odio quis lacus tincidunt suscipit ut eu sapien. Vivamus eget nisl et lacus posuere pretium sit amet vel orci. Quisque eu dapibus dui, lacinia ornare neque.';

var languageJson = {
  pt: {
    menu: ["ID", "PRÉMIOS", "LOJAS", "FAVORITOS", "GERIR"],
    loader: "Um para todos!",
    login1: {
      title1: "BEM-VINDO!",
      title2: "PARA COMEÇAR A COLECIONAR VANTAGENS",
      title3: "INSIRA O SEU NÚMERO DE TELEFONE",
      input: "Número",
      conditions: "ACEITO OS TERMOS E CONDIÇÕES",
      sendBtn: "ENVIAR",
      error: "Não é possivel efectuar o registo. Por favor tente mais tarde",
      language: "CHANGE LANGUAGE TO ENGLISH"
    },
    login2: {
      title1: "Todas as vantagens no seu telemóvel<br>totalmente grátis, para sempre!",
      title2: "INSIRA A PASSWORD QUE RECEBEU POR SMS",
      input: "Password",
      error: "PASSWORD INCORRECTA",
      sendBtn: "ENVIAR",
      title3: "NÃO RECEBEU O SMS?<br>PEÇA AQUI UM NOVO ENVIO.",
      title4: "NOVO SMS ENVIADO COM SUCESSO."
    },
    qrcode: {
      title1: "ESTE É O SEU CÓDIGO,<br>PASSE-O NAS LOJAS ADERENTES.",
      title2: "DESCUBRA EM “LOJAS” TODOS OS<br>DESCONTOS QUE ESTÃO À SUA ESPERA."
    },
    prizes: {
      search: "Pesquisar prémios",
      validity: "Válido até ",
      share: "PARTILHAR PRÉMIO",
      shareTitle: "NÚMERO DE TELEFONE DA PESSOA<br>PARA QUEM QUER ENVIAR O SEU PRÉMIO",
      contacts: "PROCURAR NOS MEUS CONTACTOS",
      insert: "INSERIR NÚMERO",
      input: "Número de telefone",
      send: "ENVIAR PRÉMIO",
      validated: "PARABÉNS!<br>O SEU PRÉMIO FOI VALIDADO<br>COM SUCESSO."
    },
    stores: {
      search: "Pesquisar lojas",
      category: "CATEGORIA",
      all: "TODOS",
      local: "LOCALIDADE",
      filter: "FILTRAR",
      checkinTitle: "CHECK-INS ACUMULADOS:",
      availablePrizes: "PRÉMIOS DISPONÍVEIS:",
      favorites: "FAVORITO",
      shareCheckIns: "PARTILHAR CHECK-INS",
      contactsAddress: "MORADA E CONTACTOS",
      shareTitle: "NÚMERO DE TELEFONE DA PESSOA<br>PARA QUEM QUER PARTILHAR OS SEUS CHECK-INS",
      contacts: "PROCURAR NOS MEUS CONTACTOS",
      insert: "INSERIR NÚMERO",
      input: "Número de telefone",
      howMany: "QUANTOS QUER PARTILHAR?",
      toShare: "Check-ins a partilhar"
    },
    manager: {
      menus: ["O MEU PERFIL", "A MINHA ACTIVIDADE", "CONTACTOS COUPZON", "F.A.Q.", "TERMOS E CONDIÇÕES", "IDIOMA"],
      contacts:{
        title1: "NÚMERO DE TELEFONE DE SUPORTE",
        title2: "EMAIL DE SUPORTE",
        title3: "MORADA"
      },
      profile:{
        name: "NOME",
        nameInput: "Inserir nome",
        number: "NÚMERO DE TELEFONE",
        password: "PASSWORD",
        change: "ALTERAR",
        email: "EMAIL",
        emailInput: "Inserir email",
        nif: "NIF",
        nifInput: "Inserir NIF",
        update: "ATUALIZAR",
        actualPassword: "PASSWORD ATUAL",
        actualPasswordInput: "Inserir password actual",
        newPassword: "NOVA PASSWORD",
        newPasswordInput: "Inserir nova password",
        confirm: "CONFIRMAR",
        alert: "PREENCHA, POR FAVOR",
        forget: "ESQUECI-ME DA PASSWORD"
      }
    },
    terms: {
      introduction: "A Coupzon com NIF XXXXX e sede na Amadora é uma empresa portuguesa que se dedica às actividades de concepção, desenvolvimento, fornecimento e documentação de programas informáticos (software) normalizados (não realizados por encomenda). Inclui a tradução e a adaptação de programas informáticos normalizados (não realizados por encomenda) para um determinado mercado, por conta própria. Compreende as actividades de fornecimento de gestão local e exploração desistemas de computadores e/ou equipamento de processamento de dados docliente, assim como serviços relacionados. Compreende as actividades de concepção, desenvolvimento, modificação,teste e assistência a programas informáticos (software), de acordo com as necessidades de um cliente específico. Inclui programação de sistemas, de aplicações, de bases de dados e de páginas Web.<br><br>OS PRESENTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO, JUNTAMENTE COM A POLÍTICA DE PRIVACIDADE INSERIDA NESTE DOCUMENTO , REGULAM AS CONDIÇÕES PELAS QUAIS O UTILIZADOR PODE FAZER USO DA COUPZON E SERVIÇOS ASSOCIADOS (WEBSITE, APPS E MOBILE WEBSITE) , PELO QUE, ACONSELHAMOS A SUA LEITURA ATENTA ANTES DE ACEDER E UTILIZAR.<br><br>AO UTILIZAR A COUPZON, O UTILIZADOR ACEITA, SEM RESERVAS, OS PRESENTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO E CONCORDA RESPEITÁ-LOS.<br><br>CASO O UTILIZADOR NÃO CONCORDE COM ESTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO NÃO DEVERÁ UTILIZAR A COUPZON.",
      title1: "1 - ACEITAÇÃO",
      description11: "1.1 - A utilização da aplicação móvel e do website, assim como dos serviços associados, dependem da aceitação destes Termos e Condições de Utilização, pelo que, caso o Utilizador não aceite estes Termos e Condições de Utilização não poderá utilizar a aplicação móvel e o website, bem como os serviços associados.",
      description12: "1.2 - Ao aceitar os Termos e Condições, o UTILIZADOR faz essa aceitação em seu nome pessoal.",
      title2: "2 - UTILIZAÇÃO DA COUPZON",
      description21: "Ao instalar a COUPZON o UTILIZADOR declara que:",
      description22: "A) É capaz de se obrigar contratual e legalmente;",
      description23: "B) Cumprirá estes Termos e Condições de Utilização.",
      title3: "3 - DIREITOS DOS UTILIZADORES",
      description31: "3.1- O UTILIZADOR pode cancelar a sua conta COUPZON a qualquer momento.",
      description32: "3.2 - Esta disposição não afeta os outros direitos legais que assistem ao UTILIZADOR enquanto consumidor.",
      title4: "4 - OBRIGAÇÕES DOS UTILIZADORES",
      description41: "4.1 - Utilizador não poderá utilizar a aplicação ou o website para fins ilícitos.",
      description42: "4.2 - O Utilizador não poderá utilizar a aplicação ou o website para:",
      item41: "a) Qualquer comportamento que viole a lei, local, nacional ou internacional;",
      item42: "b) Qualquer comportamento que seja ilegal ou fraudulento, ou que tenha qualquer propósito ou efeito ilegal ou fraudulento, obrigando-se, nomeadamente, a abster-se de qualquer comportamento ou conduta e/ou praticar qualquer ato que, direta ou indiretamente, constitua ou possa ser suscetível de constituir um aproveitamento ou exploração abusiva e fraudulenta, em benefício próprio ou de terceiros e de prejudicar a rede de lojistas ou terceiros ou qualquer outro comportamento que produza ou seja suscetível de produzir tais efeitos, nomeadamente através do preenchimento de vários formulários de registo, criando para o efeito um endereço de correio eletrónico diferente.",
      item43: "c) Prejudicar ou tentar prejudicar, por qualquer forma, menores;",
      item44: "d) Transmitir, ou procurar o envio de, qualquer tipo de publicidade ou conteúdo promocional não solicitado ou não autorizado ou qualquer outra forma de solicitação similar ('spam');",
      title6: "6 - CONTA",
      description61: "6.1 - O UTILIZADOR é único responsável pela segurança da sua conta e palavra-passe",
      description62: "6.2 - Todos os conteúdos inseridos na sua conta, assim como toda a atividade que nela tenha lugar, são da responsabilidade do UTILIZADOR.",
      description63: "6.3 - O UTILIZADOR, ao aceitar os presentes Termos e Condições de Utilização, declara que não irá usar a aplicação e/ou o website e os serviços associados à sua utilização para quaisquer fins ilegais e/ou ilícitos, que constituam uma fraude ou que não sejam autorizados.",
      title7: "7 - INTERAÇÃO DA PLATAFORMA COM O UTILIZADOR",
      description71: "7.1 - Com o objetivo de maximizar a dinamização de ofertas, e em conformidade com a Lei de Proteção de Dados e a Politica de Privacidade, o UTILIZADOR concorda que lhe sejam enviadas informações periódicas contendo resultados e outras variáveis respeitantes ao funcionamento da plataforma de fidelização, incluindo o número de compras efetuadas, descontos acumulados, ofertas em vigor, entre outros.",
      description72: "7.2 - O UTILIZADOR, em conformidade com a Lei de Proteção de Dados e a Politica de Privacidade, autoriza expressamente que os dados por si fornecidos aquando do processo de criação e registo da sua conta COUPZON, bem como os quaisquer códigos que lhe venham a ser atribuídos, façam parte integrante destas informações periódicas e que as mesmas sejam transmitidas e partilhadas com as marcas aderentes à Coupzon.",
      title9: "9 - PROPRIEDADE INTELECTUAL",
      description91: "9.1 - O UTILIZADOR reconhece que a propriedade e o título sobre todos os direitos de propriedade intelectual, incluindo-se, nomeadamente, os direitos sobre a aplicação e atualizações da mesma, códigos fonte e objeto, direitos de autor, marcas registadas e segredos comerciais, são da titularidade da COUPZON, caso os haja, dos seus respetivos licenciantes.",
      description92: "9.2 - O UTILIZADOR não copiará, traduzirá, desmontará ou descompilará, nem criará ou tentará criar, por engenharia inversa ou de outra forma, o código fonte do código objeto da aplicação e do website licenciado ao abrigo do licenciamento de utilização fornecido ao abrigo destes Termos e Condições de Utilização.",
      title10: "Politica de Privacidade",
      description10: "ACONSELHAMOS A LEITURA DESTA POLÍTICA DE PRIVACIDADE PARA CONHECER E ACEITAR AS CONDIÇÕES EM QUE DISPONIBILIZA OS SEUS DADOS PESSOAIS E AUTORIZA A SUA RECOLHA, USO E DIVULGAÇÃO DOS MESMOS DE ACORDO COM AS REGRAS AQUI DEFINIDAS.",
      title11: "ÂMBITO DE APLICAÇÃO",
      description11: "A presente Política de Privacidade aplica-se exclusivamente à recolha e tratamento de dados pessoais que é efetuada pela COUPZON para efeitos da prestação de serviços e produtos através da aplicação, permitindo desse modo que esses serviços e a aquisição dos mesmos e dos produtos decorra de forma expedita e sem transtornos para as partes envolvidas.<br><br>É obrigatório efetuar o registo de UTILIZADOR para poder efetuar a utilização de determinadas funcionalidades, nomeadamente, a identificação do UTILIZADOR nas marcas.",
      title12: "DADOS PESSOAIS",
      description12: "Dados pessoais são a informação, de qualquer natureza e suporte, incluindo-se o som e imagem, relativa a uma pessoa singular identificada ou identificável.<br><br>É considerada como identificável uma pessoa que possa ser identificada, directa ou indirectamente, designadamente por referência a um número de identificação ou a um ou mais elementos específicos da sua identidade física, fisiológica, psíquica, económica, cultural ou social.<br><br>Os seus dados pessoais irão permitir-nos prestar os serviços e produtos de forma adequada e expectável com os fins da aplicação, sendo nesse sentido uma ferramenta essencial no garante e satisfação dos UTILIZADORES da aplicação, e como tal, elemento fundamental para o sucesso reciproco de todos.",
      title13: "RESPONSÁVEL PELO TRATAMENTO",
      description13: "A COUPZON é a entidade responsável pela recolha e tratamento dos dados pessoais, decidindo as categorias de dados recolhidos, qual o tratamento dos mesmos e as finalidades para que são utilizados.",
      title14: "FINALIDADES",
      description14: "Os dados recolhidos são tratados automaticamente em conformidade com a Lei de Protecção de Dados (Lei n.º 67/98. de 26 de Outubro, LPD) e as melhores práticas, destinando-se esses dados à prestação do serviço pela COUPZON, nomeadamente, para efeitos de configuração da conta e perfil do UTILIZADOR, melhorar o conteúdo do serviço e comunicar novidades sobre ofertas especiais e novos recursos, adaptar os serviços da COUPZON às necessidades dos seus utilizadores e desenvolver novas ferramentas e, quando autorizado pelo seu titular, realizar acções de marketing por terceiros.",
      title15: "DADOS RECOLHIDOS",
      description15: "Para esses efeitos a COUPZON recolhe e trata os dados pessoais necessários à prestação dos serviços e produtos, mas igualmente à sua actividade e à gestão da aplicação, nomeadamente, nome, endereço de correio electrónico, telemóvel, data de nascimento, código postal, localidade, NIF e género.<br><br>Relativamente aos dados recolhidos pela aplicação aquando da sua utilização do serviço, esta irá registar automaticamente nos seus servidores dados gerais tais como, a plataforma móvel, localização, endereço IP e páginas solicitadas.<br><br>Aquando da utilização do serviço pode ainda ser enviada a localização do utilizador para obtenção de resultados georreferenciados, não sendo esta informação objecto de conservação pela YUNIT.",
      title16: "COMO SÃO RECOLHIDOS OS DADOS",
      description16: "A recolha de dados de identificação dos UTILIZADORES será efectuada através de número de telemóvel do UTILIZADOR.",
      title17: "UTILIZADORES",
      description17: "Dentro de um nível de segurança adequado em relação aos riscos que o tratamento apresenta e à natureza dos dados a proteger, a COUPZON, de acordo com as medidas técnicas e organizativas adequadas para proteger os dados pessoais contra a destruição, acidental ou ilícita, a perda acidental, a alteração, a difusão ou o acesso não autorizados e atendendo aos conhecimentos técnicos disponíveis, procura proteger as informações recolhidas e manter a privacidade das informações das contas dos seus UTILIZADORES, no entanto não pode garantir a segurança total das informações das contas de usuários, pelo que poderão sempre ocorrer situações de acesso ilegítimo, falhas de hardware ou software e outros factores que podem comprometer a segurança das informações dos UTILIZADORES.<br><br>Assim, para privacidade e segurança dos seus UTILIZADORES, as informações pessoais de cada UTILIZADOR são protegidas por senha.<br><br>Porém, é igualmente da responsabilidade do UTILIZADOR, efectuar uma utilização da COUPZON cuidada de modo a impedir o acesso não autorizado à conta e às suas informações pessoais, seleccionando e protegendo a sua senha adequadamente, e limitando o acesso ao dispositivo pelo qual acedeu ao serviço.",
      title18: "FINALIDADES DO TRATAMENTO",
      description18: "Os dados pessoais recolhidos têm como finalidade a gestão prestação do serviço pela COUPZON, nomeadamente, para efeitos de configuração da conta e perfil do UTILIZADOR e à gestão da aplicação.<br><br>Os dados pessoais recolhidos destinam-se igualmente à comunicação de novidades sobre ofertas especiais e novos recursos e à realização de acções de marketing por terceiros, quando autorizado pelos UTILIZADORES.",
      title19: "TEMPO DE ARMAZENAMENTO",
      description19: "O período de tempo de armazenamento dos dados varia de acordo com a finalidade para a qual a informação é tratada, podendo existir normas que obrigam ao armazenamento por um período de tempo mínimo.<br><br>Os dados serão armazenados e conservados apenas pelo período de duração do registo do UTILIZADOR, e até 1 (um) ano após o fim do registo, seja por resolução, cancelamento, suspensão ou falta de utilização da aplicação, conforme Termos e Condições da mesma, período que se entende como suficiente e necessário para as finalidades que motivaram a sua recolha e tratamento, findo o qual os mesmos serão eliminados.",
      title20: "RECTIFICAÇÃO",
      description20: "O titular dos dados poderá rectificar, actualizar e/ou modificar os seus dados a qualquer momento através da sua área de utilizador na aplicação.",
      title21: "DIREITO DE ACESSO",
      description21: "A LPD garante ao titular dos dados, o direito de acesso aos seus dados pessoais, a todo o tempo, bem como o direito de oposição à utilização dos dados facultados, devendo para tal, enviar pedido por escrito através do endereço de correio eletrónico support@coupzon.com",
      title22: "ELIMINAÇÃO",
      description22: "O titular dos dados poderá proceder à eliminação dos seus dados pessoais através do cancelamento da sua conta de UTILIZADOR, sendo contudo os dados conservados nos termos antes mencionados.",
      title23: "MEDIDAS DE SEGURANÇA",
      description23: "Dentro de um nível de segurança adequado em relação aos riscos que o tratamento apresenta e à natureza dos dados a proteger, a COUPZON garante a segurança dos dados pessoais disponibilizados através da adoção de diversas medidas de segurança, de caráter técnico e organizativo, para proteção dos dados pessoais contra a sua difusão, perda, uso indevido, alteração, tratamento ou acesso não autorizado bem como, contra qualquer outra forma de tratamento ilícito, utilizando nomeadamente o protocolo HTTP sobre uma camada adicional de segurança que utiliza o protocolo SSL/TLS (HTTPS).",
      title24: "COMUNICAÇÃO A TERCEIROS",
      description24: "As informações pessoais dos UTILIZADORES são activos da COUPZON.<br><br>A COUPZON não vende nem aluga a terceiros os dados pessoais pelos quais é responsável pelo tratamento, podendo existir apenas uma partilha dos dados pessoais nas seguintes condições:<br>No caso de a COUPZON ou parte dos seus ativos serem vendidos, ou no caso improvável de deixar de operar, as informações de utilização serão um dos ativos transferidos ou adquiridos por terceiros, ocorrendo tal operação em conformidade com a LPD.<br><br>A COUPZON poderá ainda transmitir dados a terceiros no âmbito de investigações, inquéritos e processos judiciais e/ou administrativos ou de natureza semelhante, desde que para tal seja devidamente ordenada por ordem judicial nesse sentido.",
      title25: "TRANSFERÊNCIA DOS DADOS",
      description25: "Na eventualidade de ocorrer(m) alguma(s) transferência(s) de dados para países terceiros que não pertencendo à União Europeia ou ao Espaço Económico Europeu, a COUPZON cumprirá com a LPD, nomeadamente no que respeita à adequabilidade do país de destino no que respeita a proteção de dados pessoais e aos requisitos que são aplicáveis a estas transferências, não sendo transferidos dados pessoais para jurisdições que não ofereçam garantias de segurança e proteção.",
      title26: "ALTERAÇÕES À POLITICA DE PRIVACIDADE",
      description26: "A COUPZON reserva-se no direito de reajustar ou alterar a presente Política de Privacidade, a qualquer momento, sendo essas alterações devidamente publicitadas.",
      description27: "O UTILIZADOR DECLARA TER LIDO E ENTENDIDO A PRESENTE POLITICA, CONSENTINDO NO TRATAMENTO DOS SEUS DADOS CONFORME EXPOSTO."
    }
  },
  en: {
    menu: ["ID", "PRIZES", "STORES", "FAVORITES", "MANAGE"],
    loader: "One for all!",
    login1: {
      title1: "WELCOME!",
      title2: "TO START COLLECTING ADVANTAGES",
      title3: "ENTER YOUR PHONE NUMBER",
      input: "Number",
      conditions: "I ACCEPT THE TERMS AND CONDITIONS",
      sendBtn: "SEND",
      error: "It was not possible to register. Please try again later",
      language: "MUDAR A LÍNGUA PARA PORTUGUÊS"
    },
    login2: {
      title1: "All the advantages on your phone,<br>totally free, forever!",
      title2: "INSERT PASSWORD THAT RECEIVED BY SMS",
      input: "Password",
      error: "INCORRECT PASSWORD",
      sendBtn: "SEND",
      title3: "SMS NOT RECEIVED?<br>CLICK HERE TO SEND AGAIN",
      title4: "NEW SMS SENT SUCCESSFULLY."
    },
    qrcode: {
      title1: "THIS IS YOUR CODE,<br>PASS IT IN COUPZON STORES.",
      title2: "DISCOVER IN 'STORES' ALL<br>DISCOUNTS THAT ARE WAITING FOR YOU."
    },
    prizes: {
      search: "Search prizes",
      validity: "Valid until ",
      share: "SHARE PRIZE",
      shareTitle: "PERSON PHONE NUMBER<br>TO THE ONE YOU WANT TO SEND YOUR PRIZE",
      contacts: "SEARCH IN MY CONTACTS",
      insert: "INSERT NUMBER",
      input: "Phone number",
      send: "SEND PRIZE"
    },
    stores: {
      search: "Search stores",
      category: "CATEGORY",
      all: "ALL",
      local: "LOCATION",
      filter: "FILTER",
      checkinTitle: "RETAINED CHECK-INS:",
      availablePrizes: "AVAILABLE PRIZES:",
      favorites: "FAVORITE",
      shareCheckIns: "SHARE CHECK-INS",
      contactsAddress: "ADDRESS AND CONTACTS",
      shareTitle: "PERSON PHONE NUMBER<br> TO THE ONE YOU WANT TO SEND YOUR CHECK-INS",
      contacts: "SEARCH IN MY CONTACTS",
      insert: "INSERT NUMBER",
      input: "Phone number",
      howMany: "HOW MANY WANT TO SHARE?",
      toShare: "Check-ins to share"
    },
    manager: {
      menus: ["MY PROFILE", "MY ACTIVITY", "COUPZON CONTACTS", "F.A.Q.", "TERMS AND CONDITIONS", "LANGUAGE"],
      contacts:{
        title1: "SUPPORT PHONE NUMBER",
        title2: "SUPPORT EMAIL",
        title3: "ADDRESS"
      },
      profile:{
        name: "NAME",
        nameInput: "Insert name",
        number: "PHONE NUMBER",
        password: "PASSWORD",
        change: "CHANGE",
        email: "EMAIL",
        emailInput: "Insert email",
        nif: "NIF",
        nifInput: "Insert NIF",
        update: "UPDATE",
        actualPassword: "CURRENT PASSWORD",
        actualPasswordInput: "Insert current password",
        newPassword: "NEW PASSWORD",
        newPasswordInput: "Insert new password",
        confirm: "CONFIRM",
        alert: "FILL PLEASE",
        forget: "FORGOT THE PASSWORD"
      }
    },
    terms: {
      introduction: "A Coupzon com NIF XXXXX e sede na Amadora é uma empresa portuguesa que se dedica às actividades de concepção, desenvolvimento, fornecimento e documentação de programas informáticos (software) normalizados (não realizados por encomenda). Inclui a tradução e a adaptação de programas informáticos normalizados (não realizados por encomenda) para um determinado mercado, por conta própria. Compreende as actividades de fornecimento de gestão local e exploração desistemas de computadores e/ou equipamento de processamento de dados docliente, assim como serviços relacionados. Compreende as actividades de concepção, desenvolvimento, modificação,teste e assistência a programas informáticos (software), de acordo com as necessidades de um cliente específico. Inclui programação de sistemas, de aplicações, de bases de dados e de páginas Web.<br><br>OS PRESENTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO, JUNTAMENTE COM A POLÍTICA DE PRIVACIDADE INSERIDA NESTE DOCUMENTO , REGULAM AS CONDIÇÕES PELAS QUAIS O UTILIZADOR PODE FAZER USO DA COUPZON E SERVIÇOS ASSOCIADOS (WEBSITE, APPS E MOBILE WEBSITE) , PELO QUE, ACONSELHAMOS A SUA LEITURA ATENTA ANTES DE ACEDER E UTILIZAR.<br><br>AO UTILIZAR A COUPZON, O UTILIZADOR ACEITA, SEM RESERVAS, OS PRESENTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO E CONCORDA RESPEITÁ-LOS.<br><br>CASO O UTILIZADOR NÃO CONCORDE COM ESTES TERMOS E CONDIÇÕES DE UTILIZAÇÃO NÃO DEVERÁ UTILIZAR A COUPZON.",
      title1: "1 - ACEITAÇÃO",
      description11: "1.1 - A utilização da aplicação móvel e do website, assim como dos serviços associados, dependem da aceitação destes Termos e Condições de Utilização, pelo que, caso o Utilizador não aceite estes Termos e Condições de Utilização não poderá utilizar a aplicação móvel e o website, bem como os serviços associados.",
      description12: "1.2 - Ao aceitar os Termos e Condições, o UTILIZADOR faz essa aceitação em seu nome pessoal.",
      title2: "2 - UTILIZAÇÃO DA COUPZON",
      description21: "Ao instalar a COUPZON o UTILIZADOR declara que:",
      description22: "A) É capaz de se obrigar contratual e legalmente;",
      description23: "B) Cumprirá estes Termos e Condições de Utilização.",
      title3: "3 - DIREITOS DOS UTILIZADORES",
      description31: "3.1- O UTILIZADOR pode cancelar a sua conta COUPZON a qualquer momento.",
      description32: "3.2 - Esta disposição não afeta os outros direitos legais que assistem ao UTILIZADOR enquanto consumidor.",
      title4: "4 - OBRIGAÇÕES DOS UTILIZADORES",
      description41: "4.1 - Utilizador não poderá utilizar a aplicação ou o website para fins ilícitos.",
      description42: "4.2 - O Utilizador não poderá utilizar a aplicação ou o website para:",
      item41: "a) Qualquer comportamento que viole a lei, local, nacional ou internacional;",
      item42: "b) Qualquer comportamento que seja ilegal ou fraudulento, ou que tenha qualquer propósito ou efeito ilegal ou fraudulento, obrigando-se, nomeadamente, a abster-se de qualquer comportamento ou conduta e/ou praticar qualquer ato que, direta ou indiretamente, constitua ou possa ser suscetível de constituir um aproveitamento ou exploração abusiva e fraudulenta, em benefício próprio ou de terceiros e de prejudicar a rede de lojistas ou terceiros ou qualquer outro comportamento que produza ou seja suscetível de produzir tais efeitos, nomeadamente através do preenchimento de vários formulários de registo, criando para o efeito um endereço de correio eletrónico diferente.",
      item43: "c) Prejudicar ou tentar prejudicar, por qualquer forma, menores;",
      item44: "d) Transmitir, ou procurar o envio de, qualquer tipo de publicidade ou conteúdo promocional não solicitado ou não autorizado ou qualquer outra forma de solicitação similar ('spam');",
      title6: "6 - CONTA",
      description61: "6.1 - O UTILIZADOR é único responsável pela segurança da sua conta e palavra-passe",
      description62: "6.2 - Todos os conteúdos inseridos na sua conta, assim como toda a atividade que nela tenha lugar, são da responsabilidade do UTILIZADOR.",
      description63: "6.3 - O UTILIZADOR, ao aceitar os presentes Termos e Condições de Utilização, declara que não irá usar a aplicação e/ou o website e os serviços associados à sua utilização para quaisquer fins ilegais e/ou ilícitos, que constituam uma fraude ou que não sejam autorizados.",
      title7: "7 - INTERAÇÃO DA PLATAFORMA COM O UTILIZADOR",
      description71: "7.1 - Com o objetivo de maximizar a dinamização de ofertas, e em conformidade com a Lei de Proteção de Dados e a Politica de Privacidade, o UTILIZADOR concorda que lhe sejam enviadas informações periódicas contendo resultados e outras variáveis respeitantes ao funcionamento da plataforma de fidelização, incluindo o número de compras efetuadas, descontos acumulados, ofertas em vigor, entre outros.",
      description72: "7.2 - O UTILIZADOR, em conformidade com a Lei de Proteção de Dados e a Politica de Privacidade, autoriza expressamente que os dados por si fornecidos aquando do processo de criação e registo da sua conta COUPZON, bem como os quaisquer códigos que lhe venham a ser atribuídos, façam parte integrante destas informações periódicas e que as mesmas sejam transmitidas e partilhadas com as marcas aderentes à Coupzon.",
      title9: "9 - PROPRIEDADE INTELECTUAL",
      description91: "9.1 - O UTILIZADOR reconhece que a propriedade e o título sobre todos os direitos de propriedade intelectual, incluindo-se, nomeadamente, os direitos sobre a aplicação e atualizações da mesma, códigos fonte e objeto, direitos de autor, marcas registadas e segredos comerciais, são da titularidade da COUPZON, caso os haja, dos seus respetivos licenciantes.",
      description92: "9.2 - O UTILIZADOR não copiará, traduzirá, desmontará ou descompilará, nem criará ou tentará criar, por engenharia inversa ou de outra forma, o código fonte do código objeto da aplicação e do website licenciado ao abrigo do licenciamento de utilização fornecido ao abrigo destes Termos e Condições de Utilização.",
      title10: "Politica de Privacidade",
      description10: "ACONSELHAMOS A LEITURA DESTA POLÍTICA DE PRIVACIDADE PARA CONHECER E ACEITAR AS CONDIÇÕES EM QUE DISPONIBILIZA OS SEUS DADOS PESSOAIS E AUTORIZA A SUA RECOLHA, USO E DIVULGAÇÃO DOS MESMOS DE ACORDO COM AS REGRAS AQUI DEFINIDAS.",
      title11: "ÂMBITO DE APLICAÇÃO",
      description11: "A presente Política de Privacidade aplica-se exclusivamente à recolha e tratamento de dados pessoais que é efetuada pela COUPZON para efeitos da prestação de serviços e produtos através da aplicação, permitindo desse modo que esses serviços e a aquisição dos mesmos e dos produtos decorra de forma expedita e sem transtornos para as partes envolvidas.<br><br>É obrigatório efetuar o registo de UTILIZADOR para poder efetuar a utilização de determinadas funcionalidades, nomeadamente, a identificação do UTILIZADOR nas marcas.",
      title12: "DADOS PESSOAIS",
      description12: "Dados pessoais são a informação, de qualquer natureza e suporte, incluindo-se o som e imagem, relativa a uma pessoa singular identificada ou identificável.<br><br>É considerada como identificável uma pessoa que possa ser identificada, directa ou indirectamente, designadamente por referência a um número de identificação ou a um ou mais elementos específicos da sua identidade física, fisiológica, psíquica, económica, cultural ou social.<br><br>Os seus dados pessoais irão permitir-nos prestar os serviços e produtos de forma adequada e expectável com os fins da aplicação, sendo nesse sentido uma ferramenta essencial no garante e satisfação dos UTILIZADORES da aplicação, e como tal, elemento fundamental para o sucesso reciproco de todos.",
      title13: "RESPONSÁVEL PELO TRATAMENTO",
      description13: "A COUPZON é a entidade responsável pela recolha e tratamento dos dados pessoais, decidindo as categorias de dados recolhidos, qual o tratamento dos mesmos e as finalidades para que são utilizados.",
      title14: "FINALIDADES",
      description14: "Os dados recolhidos são tratados automaticamente em conformidade com a Lei de Protecção de Dados (Lei n.º 67/98. de 26 de Outubro, LPD) e as melhores práticas, destinando-se esses dados à prestação do serviço pela COUPZON, nomeadamente, para efeitos de configuração da conta e perfil do UTILIZADOR, melhorar o conteúdo do serviço e comunicar novidades sobre ofertas especiais e novos recursos, adaptar os serviços da COUPZON às necessidades dos seus utilizadores e desenvolver novas ferramentas e, quando autorizado pelo seu titular, realizar acções de marketing por terceiros.",
      title15: "DADOS RECOLHIDOS",
      description15: "Para esses efeitos a COUPZON recolhe e trata os dados pessoais necessários à prestação dos serviços e produtos, mas igualmente à sua actividade e à gestão da aplicação, nomeadamente, nome, endereço de correio electrónico, telemóvel, data de nascimento, código postal, localidade, NIF e género.<br><br>Relativamente aos dados recolhidos pela aplicação aquando da sua utilização do serviço, esta irá registar automaticamente nos seus servidores dados gerais tais como, a plataforma móvel, localização, endereço IP e páginas solicitadas.<br><br>Aquando da utilização do serviço pode ainda ser enviada a localização do utilizador para obtenção de resultados georreferenciados, não sendo esta informação objecto de conservação pela YUNIT.",
      title16: "COMO SÃO RECOLHIDOS OS DADOS",
      description16: "A recolha de dados de identificação dos UTILIZADORES será efectuada através de número de telemóvel do UTILIZADOR.",
      title17: "UTILIZADORES",
      description17: "Dentro de um nível de segurança adequado em relação aos riscos que o tratamento apresenta e à natureza dos dados a proteger, a COUPZON, de acordo com as medidas técnicas e organizativas adequadas para proteger os dados pessoais contra a destruição, acidental ou ilícita, a perda acidental, a alteração, a difusão ou o acesso não autorizados e atendendo aos conhecimentos técnicos disponíveis, procura proteger as informações recolhidas e manter a privacidade das informações das contas dos seus UTILIZADORES, no entanto não pode garantir a segurança total das informações das contas de usuários, pelo que poderão sempre ocorrer situações de acesso ilegítimo, falhas de hardware ou software e outros factores que podem comprometer a segurança das informações dos UTILIZADORES.<br><br>Assim, para privacidade e segurança dos seus UTILIZADORES, as informações pessoais de cada UTILIZADOR são protegidas por senha.<br><br>Porém, é igualmente da responsabilidade do UTILIZADOR, efectuar uma utilização da COUPZON cuidada de modo a impedir o acesso não autorizado à conta e às suas informações pessoais, seleccionando e protegendo a sua senha adequadamente, e limitando o acesso ao dispositivo pelo qual acedeu ao serviço.",
      title18: "FINALIDADES DO TRATAMENTO",
      description18: "Os dados pessoais recolhidos têm como finalidade a gestão prestação do serviço pela COUPZON, nomeadamente, para efeitos de configuração da conta e perfil do UTILIZADOR e à gestão da aplicação.<br><br>Os dados pessoais recolhidos destinam-se igualmente à comunicação de novidades sobre ofertas especiais e novos recursos e à realização de acções de marketing por terceiros, quando autorizado pelos UTILIZADORES.",
      title19: "TEMPO DE ARMAZENAMENTO",
      description19: "O período de tempo de armazenamento dos dados varia de acordo com a finalidade para a qual a informação é tratada, podendo existir normas que obrigam ao armazenamento por um período de tempo mínimo.<br><br>Os dados serão armazenados e conservados apenas pelo período de duração do registo do UTILIZADOR, e até 1 (um) ano após o fim do registo, seja por resolução, cancelamento, suspensão ou falta de utilização da aplicação, conforme Termos e Condições da mesma, período que se entende como suficiente e necessário para as finalidades que motivaram a sua recolha e tratamento, findo o qual os mesmos serão eliminados.",
      title20: "RECTIFICAÇÃO",
      description20: "O titular dos dados poderá rectificar, actualizar e/ou modificar os seus dados a qualquer momento através da sua área de utilizador na aplicação.",
      title21: "DIREITO DE ACESSO",
      description21: "A LPD garante ao titular dos dados, o direito de acesso aos seus dados pessoais, a todo o tempo, bem como o direito de oposição à utilização dos dados facultados, devendo para tal, enviar pedido por escrito através do endereço de correio eletrónico support@coupzon.com",
      title22: "ELIMINAÇÃO",
      description22: "O titular dos dados poderá proceder à eliminação dos seus dados pessoais através do cancelamento da sua conta de UTILIZADOR, sendo contudo os dados conservados nos termos antes mencionados.",
      title23: "MEDIDAS DE SEGURANÇA",
      description23: "Dentro de um nível de segurança adequado em relação aos riscos que o tratamento apresenta e à natureza dos dados a proteger, a COUPZON garante a segurança dos dados pessoais disponibilizados através da adoção de diversas medidas de segurança, de caráter técnico e organizativo, para proteção dos dados pessoais contra a sua difusão, perda, uso indevido, alteração, tratamento ou acesso não autorizado bem como, contra qualquer outra forma de tratamento ilícito, utilizando nomeadamente o protocolo HTTP sobre uma camada adicional de segurança que utiliza o protocolo SSL/TLS (HTTPS).",
      title24: "COMUNICAÇÃO A TERCEIROS",
      description24: "As informações pessoais dos UTILIZADORES são activos da COUPZON.<br><br>A COUPZON não vende nem aluga a terceiros os dados pessoais pelos quais é responsável pelo tratamento, podendo existir apenas uma partilha dos dados pessoais nas seguintes condições:<br>No caso de a COUPZON ou parte dos seus ativos serem vendidos, ou no caso improvável de deixar de operar, as informações de utilização serão um dos ativos transferidos ou adquiridos por terceiros, ocorrendo tal operação em conformidade com a LPD.<br><br>A COUPZON poderá ainda transmitir dados a terceiros no âmbito de investigações, inquéritos e processos judiciais e/ou administrativos ou de natureza semelhante, desde que para tal seja devidamente ordenada por ordem judicial nesse sentido.",
      title25: "TRANSFERÊNCIA DOS DADOS",
      description25: "Na eventualidade de ocorrer(m) alguma(s) transferência(s) de dados para países terceiros que não pertencendo à União Europeia ou ao Espaço Económico Europeu, a COUPZON cumprirá com a LPD, nomeadamente no que respeita à adequabilidade do país de destino no que respeita a proteção de dados pessoais e aos requisitos que são aplicáveis a estas transferências, não sendo transferidos dados pessoais para jurisdições que não ofereçam garantias de segurança e proteção.",
      title26: "ALTERAÇÕES À POLITICA DE PRIVACIDADE",
      description26: "A COUPZON reserva-se no direito de reajustar ou alterar a presente Política de Privacidade, a qualquer momento, sendo essas alterações devidamente publicitadas.",
      description27: "O UTILIZADOR DECLARA TER LIDO E ENTENDIDO A PRESENTE POLITICA, CONSENTINDO NO TRATAMENTO DOS SEUS DADOS CONFORME EXPOSTO."
    }
  }
}